name = "nuxt-worker-demo"
main = "src/index.ts"
compatibility_date = "2024-07-25"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]
